"""adiciona coluna telefone ao paciente

Revision ID: be28a69254a2
Revises: c39460d0ac88
Create Date: 2026-04-22 23:53:42.009046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be28a69254a2'
down_revision: Union[str, Sequence[str], None] = 'c39460d0ac88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Adiciona coluna telefone à tabela Paciente para envio de lembretes via SMS/WhatsApp."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte adição da coluna telefone."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
