"""migração inicial - Fila Zero Saúde

Revision ID: c39460d0ac88
Revises: 
Create Date: 2026-04-12 22:19:16.465149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39460d0ac88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Cria as tabelas iniciais do sistema Fila Zero Saúde (Paciente e Consulta)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Paciente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('credencial', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Consulta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.Column('unidade_saude', sa.String(), nullable=True),
    sa.Column('data_consulta', sa.String(), nullable=True),
    sa.Column('horario', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['Paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove as tabelas do sistema Fila Zero Saúde."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Consulta')
    op.drop_table('Paciente')
    # ### end Alembic commands ###
